<img align="left" src="./img/lu.png" hspace="20"/> <img align="right" src="./img/midlands+.png"/> 
<br/><br/><br/><br/><br/><br/><br/>

------


## NumPy
[Numpy]( http://www.numpy.org/) is a Python extension package that is designed for scientific computation. It provides high-performance data structures for efficient manipulation of multi-dimensional arrays and matrices, also known as *array-oriented computing*. In addition, NumPy supplies many high-level mathematical functions that can operate on these arrays and matrices.

NumPy is not included in the default Python. Users can install it through [the Python Package Index](https://pypi.org/),  `pip install numpy` for example. To use NumPy, import NumPy to your current namespace:

In [1]:
from __future__ import print_function
import numpy as np

np.sum([1, 2, 3, 4])

10

------

### Creating NumPy arrays
* Manually construct an array from a Python list or tuple using the NumPy `array` function

In [2]:
a = np.array([1, 2, 3, 4])  # from list
b = np.array((5.6, 6.7, 7.8, 8.9, 9.))  # from tuple
print(a)
print(b)
print(a.ndim)  # 1D array
print(a.shape)
print(a.size)
print(a.dtype)

[1 2 3 4]
[5.6 6.7 7.8 8.9 9. ]
1
(4,)
4
int32


Both array `a` and `b` have a NumPy type of `ndarray`:  

In [3]:
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

2D array:

In [4]:
c = np.array([[1., 2., 3., 4.], [5., 6., 7., 8.]])
print(c)
print(c.ndim)  # 2D array
print(c.shape)  # the shape is 2 x 4
print(c.size)
print(c.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
2
(2, 4)
8
float64


Datatype can also be specified during array creation:

In [5]:
d = np.array([[1, 2, 3], [10, 20, 30]], dtype='float64')
print(d.dtype)

float64


* Create an array using functions

	`np.arange()` and `np.linspace()` are usually used to construct evenly-spaced arrays. The former specifies the start, end and increment values, whilst the latter returns a 1-D array by giving the start, end and number of elements.

In [6]:
# In practice, we rarely enter elements one by one.
e = np.arange(6)  # from 0 to n-1 with an increment of 1
print(e)

# Or specify the start, end and increment values
f = np.arange(2, 10, 2)
print(f)

# Or use the linspace function that is similar to that of Matlab
g = np.linspace(2, 13, 12)  # start, end and number of elements
print(g)

[0 1 2 3 4 5]
[2 4 6 8]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]


We can then reshape it to different shapes:

In [7]:
h = g.reshape([2, 6])  # 2D
print(h)
print('\n\n')

i = g.reshape([2, 2, 3])  # 3D
print(i)

[[ 2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13.]]



[[[ 2.  3.  4.]
  [ 5.  6.  7.]]

 [[ 8.  9. 10.]
  [11. 12. 13.]]]


 `np.ones()`, `np.zeros()`, `np.random()`, `np.empty()` and `np.full()` are often used to create arrays that have known shapes.

In [8]:
# Create an array of ones
print('np.ones():\n', np.ones((2, 3)), '\n')

# Create an array of zeros
print('np.zeros():\n', np.zeros((2, 3, 4), dtype=np.int32), '\n')

# Create an array with random values
print('np.random():\n', np.random.random((2, 2)), '\n')

# Create an empty array that has a shape of 3x2
print('np.empty():\n', np.empty((3, 2)), '\n')

# Create a full array that has a shape of 3x2 and is filled with number 10
print('np.full():\n', np.full((3, 2), 10), '\n')

np.ones():
 [[1. 1. 1.]
 [1. 1. 1.]] 

np.zeros():
 [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]] 

np.random():
 [[0.69900363 0.48865653]
 [0.55812573 0.31788455]] 

np.empty():
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 

np.full():
 [[10 10]
 [10 10]
 [10 10]] 



`np.eye()` creates a 2-D array with ones on the diagonal and zeros elsewhere, while `np.diag()` returns a diagonal 2-D array from a 1-D array specified by the user.

In [9]:
print('np.eye():\n', np.eye(3), '\n')

print('np.diag():\n', np.diag((2, 3, 4, 5)))

np.eye():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

np.diag():
 [[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


`np.mgrid()` returns a dense multi-dimensional “meshgrid”.

In [10]:
x, y = np.mgrid[0:4, 1:6]
print('x: \n', x, '\n')
print('y: \n', y, '\n')

x: 
 [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]] 

y: 
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]] 



------

### Indexing and slicing

1-D arrays can be indexed and sliced by using the square bracket and positional indices, much like the Python lists. NumPy array index starts from `0` and accepts both positive and negative indices. The former counts from the beginning while the latter counts from the end of the array.

In [11]:
a = np.arange(10)
print('Array a: ', a[:])
print('The first element of a: ', a[0])
print('The last element of a: ', a[-1])
print('The first 3 elements of a: ', a[:3])
print('The last 3 elements of a: ', a[-3:])
print('Elements from the third to the end: ', a[2:])
print('Elements from the third to the eighth: ', a[2:8])
print('Elements from the start to the end with a step of 1: ', a[::])
print('Elements from the start to the end with a step of 2: ', a[::2])
print('Elements from the third to the eighth with a step of 2: ', a[2:8:2])

Array a:  [0 1 2 3 4 5 6 7 8 9]
The first element of a:  0
The last element of a:  9
The first 3 elements of a:  [0 1 2]
The last 3 elements of a:  [7 8 9]
Elements from the third to the end:  [2 3 4 5 6 7 8 9]
Elements from the third to the eighth:  [2 3 4 5 6 7]
Elements from the start to the end with a step of 1:  [0 1 2 3 4 5 6 7 8 9]
Elements from the start to the end with a step of 2:  [0 2 4 6 8]
Elements from the third to the eighth with a step of 2:  [2 4 6]


Multidimensional arrays can be indexed and sliced by specifying one index per axis. Each axis accepts the indexing rules described above.

In [12]:
# Here we use list comprehension to construct a 2-D array
b = np.array([[m + n for m in np.arange(6)] for n in np.arange(4)])
print('Array b:\n', b[:, :], '\n')
print('The second row: ', b[1, :], '\n')
print('A subset of array b:\n', b[1:4, 2:4])

Array b:
 [[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]] 

The second row:  [1 2 3 4 5 6] 

A subset of array b:
 [[3 4]
 [4 5]
 [5 6]]


When fewer indices are provided compared to the dimension of the array,  the non-supplied indices will be set to be the complete `:`.

In [13]:
print('The first row: ', b[0])  # equivalent to b[0, :]

The first row:  [0 1 2 3 4 5]


An integer array or list can also be used in-place as indices: 

In [14]:
idx_row = np.array([0, 2, 3])
idx_col = np.array([1, 3, 5])
print('b[idx_row]:\n', b[idx_row], '\n')
print('b[idx_col]:\n', b[:, idx_col], '\n')
print('b[idx_row, idx_col]:\n', b[idx_row, idx_col])

b[idx_row]:
 [[0 1 2 3 4 5]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]] 

b[idx_col]:
 [[1 3 5]
 [2 4 6]
 [3 5 7]
 [4 6 8]] 

b[idx_row, idx_col]:
 [1 5 8]


Indexing NumPy arrays with Boolean masks is very useful to access and process array elements selectively. We can use an array with bool datatype as the index array, and the element where its index value is true is selected.

In [15]:
masks = np.array([[0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1]], dtype=bool)
print('b:\n', b, '\n')
print('masks:\n', masks, '\n')
print('Masked b:\n', b[masks])

b:
 [[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]] 

masks:
 [[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]] 

Masked b:
 [1 3 5 2 4 6 3 5 7 4 6 8]


Applying logical conditions to an array will return a Boolean array that can be used as masks, extracting elements greater than 2 for example.

In [16]:
b[b > 2]

array([3, 4, 5, 3, 4, 5, 6, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 8])

------

### Operations
#### Arithmetic operations
`+`, `-`, `*` and `/` can be performed between two NumPy arrays or between a scalar and an array in a way of element-wise operation. 

In [17]:
a = 10.5
array1 = np.array([[m + n for m in np.arange(6)] for n in np.arange(4)], dtype=np.float32)  # 4 x 6 2D arrays
array2 = np.array([[m - n for m in np.arange(6)] for n in np.arange(4)], dtype=np.float32)  # 4 x 6 2D arrays

In [18]:
print(array1 + a, '\n')
print(array1 - array2, '\n')
print(array1 / a, '\n')
print(array1 * array2)

[[10.5 11.5 12.5 13.5 14.5 15.5]
 [11.5 12.5 13.5 14.5 15.5 16.5]
 [12.5 13.5 14.5 15.5 16.5 17.5]
 [13.5 14.5 15.5 16.5 17.5 18.5]] 

[[0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4.]
 [6. 6. 6. 6. 6. 6.]] 

[[0.         0.0952381  0.1904762  0.2857143  0.3809524  0.47619048]
 [0.0952381  0.1904762  0.2857143  0.3809524  0.47619048 0.5714286 ]
 [0.1904762  0.2857143  0.3809524  0.47619048 0.5714286  0.6666667 ]
 [0.2857143  0.3809524  0.47619048 0.5714286  0.6666667  0.7619048 ]] 

[[ 0.  1.  4.  9. 16. 25.]
 [-1.  0.  3.  8. 15. 24.]
 [-4. -3.  0.  5. 12. 21.]
 [-9. -8. -5.  0.  7. 16.]]


`+=`, `-=`, `*=` and `/=` that are different from the normal operations above will act in place to modify the existing arrays rather than creating new ones. 

In [19]:
array3 = np.array(np.arange(10), dtype=float)
print(array3)
array3 += 2.5
print(array3)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5]


#### Matrix algebra

Array manipulation is NOT matrix manipulation. The former is element-wise operation while the later follows the rules of algebra. If we use the NumPy arrays as the input parameters of algebra functions (e.g. the dot product `np.dot()`), the shapes of two arrays should match the algebra rules.

In [20]:
A = np.array([[m + n for m in np.arange(4)] for n in np.arange(4)])  # 4 x 4 2D arrays
B = np.array([[m - n for m in np.arange(3)] for n in np.arange(4)])  # 4 x 3 2D arrays
C = np.arange(4)  # 1D vector with a size of 4
A, B, C

(array([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]]), array([[ 0,  1,  2],
        [-1,  0,  1],
        [-2, -1,  0],
        [-3, -2, -1]]), array([0, 1, 2, 3]))

In [21]:
print(np.dot(A, B), '\n')
print(np.dot(A, C))

[[-14  -8  -2]
 [-20 -10   0]
 [-26 -12   2]
 [-32 -14   4]]

 

[14 20 26 32]


Alternatively, we can cast the NumPy arrays to NumPy matrix objects by using `np.matrix()`.

In [22]:
AM = np.matrix(A)
BM = np.matrix(B)
CM = np.matrix(C)
AM, BM, CM

(matrix([[0, 1, 2, 3],
         [1, 2, 3, 4],
         [2, 3, 4, 5],
         [3, 4, 5, 6]]), matrix([[ 0,  1,  2],
         [-1,  0,  1],
         [-2, -1,  0],
         [-3, -2, -1]]), matrix([[0, 1, 2, 3]]))

Then, we can use `+`, `-`, and `*` for matrix algebra directly. Note that the shapes should be compatible with matrix algebra, otherwise an error will be returned. 

In [23]:
# dot product
AM * BM

matrix([[-14,  -8,  -2],
        [-20, -10,   0],
        [-26, -12,   2],
        [-32, -14,   4]])

In [24]:
AM * CM.T  # here .T means Transport that converts CM to a column vector

matrix([[14],
        [20],
        [26],
        [32]])

In [25]:
# inner product
CM * CM.T  # you can also use np.inner() function

matrix([[14]])

In [26]:
# outer product
CM.T * CM  # you can also use np.outer() function

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [27]:
# Matrix addition
CM.T + AM * CM.T

matrix([[14],
        [21],
        [28],
        [35]])

Determinant and Inverse of matrices:

In [28]:
# Determinant
M = np.array([[6, 1, 2], [2, -4, 6], [3, 5, 8]])
np.linalg.det(M)

-326.0

In [29]:
# Inverse
np.linalg.inv(M)

array([[ 0.19018405, -0.00613497, -0.04294479],
       [-0.00613497, -0.12883436,  0.09815951],
       [-0.06748466,  0.08282209,  0.0797546 ]])

#### Other functions

NumPy provides with many statistical functions that can be used for data processing, `np.sum()`, `np.mean()`, `np.min()`, `np.max()`, `np.std()`, `np.var()`, `np.prod()`, and `np.trace()` for example, and other mathematical functions such as trigonometric functions and functions for rounding numbers. A full list of mathematical functions is available [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html).

------

### Copies and Views

Memory handling in Python can be tricky. For array manipulations some operations copy array data to a new array and some don’t. That is quite confusing especially for beginners. Let’s take a look at what are _copies_ and _views_.
 
#### No copy
Array assignment will not copy array data. What it is doing is just give the array an alias. Changes made to the new objects will be propagated to the raw array.

In [30]:
D = np.array([1, 2, 3, 4, 5])
D

array([1, 2, 3, 4, 5])

In [31]:
D1 = D
D1 is D

True

In [32]:
D1[0:2] = 100  # we change D1
print(D)  # D is also changed

[100 100   3   4   5]


Python functions pass mutable objects as references. 

In [33]:
def myfunc(a):
    a[:] = -10
    
myfunc(D)
D

array([-10, -10, -10, -10, -10])

#### View and shallow copy
Different objects can share the same data (same memory) and represent the same data in different forms (e.g. different shapes). This is what `view` is doing. 

In [34]:
E = np.array([1, 2, 3, 4, 5, 6])
E

array([1, 2, 3, 4, 5, 6])

In [35]:
E1 = E.view()
E1

array([1, 2, 3, 4, 5, 6])

In [36]:
E1 is E

False

In [37]:
E1.shape = (3, 2)  # now E1's shape is 3x2
E1.shape

(3, 2)

In [38]:
E.shape

(6,)

In [39]:
E1[0, :] = 0  # Now we change E1
E  # E is also changed 

array([0, 0, 3, 4, 5, 6])

Slicing operation returns a view of array.

In [40]:
E2 = E[2:]
E2

array([3, 4, 5, 6])

In [41]:
E2[:] = 0  # change E2
E  # E also changed

array([0, 0, 0, 0, 0, 0])

#### Deep copy
Deep copy means making a new copy of data completely. This is done by the `copy` function.

In [42]:
E3 = E.copy()
E3

array([0, 0, 0, 0, 0, 0])

In [43]:
E3[:] = 100  # E3 has been changed
E  # E is not affected

array([0, 0, 0, 0, 0, 0])

To prevent changes from functions, we need to pass a copy of array to the function.

In [44]:
myfunc(E.copy())
E

array([0, 0, 0, 0, 0, 0])

In [45]:
# If we pass E directly to the function
myfunc(E)
E

array([-10, -10, -10, -10, -10, -10])

------

### Manipulating arrays
#### Flattening, reshaping and resizing
A multidimensional array can be flattened to a 1D vector by using the build-in `flatten` or `ravel` methods of the array object. The former returns a copy of array while the latter returns a view.    

In [46]:
A

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [47]:
A1 = A.flatten()
A1

array([0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6])

In [48]:
# change A1
A1[1:6] = 99
A1

array([ 0, 99, 99, 99, 99, 99,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6])

In [49]:
# verify A
A

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [50]:
A2 = A.ravel()
A2[1:6] = 99  # we change A2
A  # A is changed

array([[ 0, 99, 99, 99],
       [99, 99,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6]])

An array can be reshaped to other shapes by using the object `reshape` method or the `np.reshape` function. Both return a view of array. To be able to reshape an array, the size of the new shape must match the number of the elements of the array that is to be reshaped. For example, array A has 16 elements and we can reshape it to `(4, 4)`, `(2, 8)` or `(2, 2, 4)`, but not `(3, 4)`, `(3, 8)` or other shapes that do not match the size of the array.

In [51]:
A3 = A.reshape(2, 8)
A3

array([[ 0, 99, 99, 99, 99, 99,  3,  4],
       [ 2,  3,  4,  5,  3,  4,  5,  6]])

In [52]:
# let's introduce changes to A3
A3[0, 1:6] = 100
A

array([[  0, 100, 100, 100],
       [100, 100,   3,   4],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6]])

In [53]:
A4 = np.reshape(A, (2, 8))
A4

array([[  0, 100, 100, 100, 100, 100,   3,   4],
       [  2,   3,   4,   5,   3,   4,   5,   6]])

In [54]:
A4[0, 1:6] = 200
A

array([[  0, 200, 200, 200],
       [200, 200,   3,   4],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6]])

You can also reshape the array in place:

In [55]:
A.shape = (2, 8)
A

array([[  0, 200, 200, 200, 200, 200,   3,   4],
       [  2,   3,   4,   5,   3,   4,   5,   6]])

Let's calculate the values at many `x` and `y` points:

In [56]:
F = np.array([[m + n + 1 for m in np.arange(3)] for n in np.arange(5)])  # 5 x 3 2D arrays with a size of 15
F.resize(20)  # we change the size from 15 to 20
F

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6, 5, 6, 7, 0, 0, 0, 0, 0])

If the new size if larger than the old one, `0` will be used to fill in the gaps. 

#### Array axis
NumPy allows users to apply operations on specific axis of arrays, the dimension of which is greater than 1.

In [57]:
F = np.array([[m + n + 1 for m in np.arange(3)] for n in np.arange(5)])
F

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [58]:
F.sum(axis=1)

array([ 6,  9, 12, 15, 18])

We can add new axis to convert a column vector to a row vector, or the other way round.

In [59]:
F = np.array([1, 2, 3, 4, 5])
F

array([1, 2, 3, 4, 5])

In [60]:
F.shape

(5,)

In [61]:
F[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [62]:
F[:, np.newaxis].shape

(5, 1)

#### Stacking, splitting and repeating arrays
Several arrays can be stacked together along different axes using the `vstack`, `hstack` and `concatenate` functions. `vstack` and `hstack` stack two arrays along vertical and horizontal axis respectively, while `concatenate` allows to specify the axis along which concatenate should occur. 

In [63]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10, 20, 30], [40, 50, 60]])
np.vstack([a, b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [64]:
np.hstack([a, b])

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [65]:
np.concatenate((a, b), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [66]:
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

Similarly, to split an array to several sub-arrays, use `vsplit` and `hsplit` functions.

In [67]:
np.vsplit(a, 2)  # split into 2 arrays

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [68]:
np.hsplit(a, 3)  # split into 2 arrays

[array([[1],
        [4]]), array([[2],
        [5]]), array([[3],
        [6]])]

In [69]:
np.hsplit(a, (1, 2))  # split after the first and second column

[array([[1],
        [4]]), array([[2],
        [5]]), array([[3],
        [6]])]

We can repeat an array to construct a larger array using the `repeat` and `tile` functions.

In [70]:
np.repeat(a, 3)  # Repeat a by 3 times 

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [71]:
np.tile(a, 3)  # 3 tiles

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [72]:
# clone a row vector 3 times to form a 2D array
b = np.array([1, 2, 3, 4, 5])
np.repeat(b[np.newaxis, :], 3, 0)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [73]:
# Or use the tile function
np.tile(b, (3, 1))  # repeat b 3 times in row and 1 in column

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

#### Conditions
In practice, it is very common to manipulate arrays conditionally. `np.where` function can process the elements that satisfy the condtions specified by users. See the examples below:

In [74]:
c = np.array([[m + n + 1 for m in np.arange(8)] for n in np.arange(3)])
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

In [75]:
# If 8 > value > 3, set value = 1;
c[np.where((c > 3) & (c < 8))] = 1
c

array([[ 1,  2,  3,  1,  1,  1,  1,  8],
       [ 2,  3,  1,  1,  1,  1,  8,  9],
       [ 3,  1,  1,  1,  1,  8,  9, 10]])

In [76]:
# another array that has the same shape
d = np.array([[m + n - 2 for m in np.arange(8)] for n in np.arange(3)])
d

array([[-2, -1,  0,  1,  2,  3,  4,  5],
       [-1,  0,  1,  2,  3,  4,  5,  6],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [77]:
# get the bigger elements of two arrays
np.where(c > d, c, d)  # if condition is true, take element from c, otherwise from d.

array([[ 1,  2,  3,  1,  2,  3,  4,  8],
       [ 2,  3,  1,  2,  3,  4,  8,  9],
       [ 3,  1,  2,  3,  4,  8,  9, 10]])

#### Broadcasting
Broadcasting is a powerful feature of Numpy. As mentioned previously, array operations in Numpy are elementwise and work on arrays of the same size. However, it is also possible to perform operations on arrays of different sizes if the arrays can be transformed to the same shapes by following certain rules. Such transformation is called _broadcasting_. It allows Numpy to operate arrays that have different dimensions.

The dimensions of two arrays are compatible when they are equal or one of them is 1. If the two conditions are met, then array operations can be performed. Otherwise, Python will throw an error. Broadcasting occurs by following the two rules below:

* If the number of the dimensions of two arrays is different ( e.g. shape (3, 4) and shape (4) ),  a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions (e.g. shape (4) -> shape (1, 4))
* Start with the trailing dimensions and work its way forward. If the size of an array along a dimension is 1, then the size is stretched to be as the same as that of another array. The values of the first data entry in that dimension will be used repeatedly along the stretched dimension

See the example below:

In [78]:
a1 = np.array([[m + n for m in np.arange(8)] for n in np.arange(3)])  # shape (3, 8)
a1

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8, 9]])

In [79]:
a2 = np.arange(8)  # shape (8,)
a2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [80]:
a1 + a2  # a1 and a2 have different shapes, but we can still perform operations

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

Let’s split the broadcasting steps manually. Apply the first rule first:

In [81]:
a2 = a2[np.newaxis, :]  # see np.newaxis examples in previous sections
a2.shape

(1, 8)

Now array a2 has the same number of dimensions as a1 (*ndim*), which is 2. But a1 and a2 still have different shapes. Following rule 2, we repeat a2 3 times along its first dimension by using np.repeat function:  

In [82]:
a2 = np.repeat(a2, 3, 0)
a2

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [83]:
# now a1 and a2 have the same shapes
a1 + a2

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

#### Vectorisation
The key element of NumPy is about vectorisation that is the main difficulty of Python for the performance of scientific computing. So far you have already seen a lot of vectorised operations applied on NumPy arrays and matrices by using the build-in NumPy functions (such as `np.add()`, `np.dot()`, and `np.multiply()`). These operations are in a way of element-wise and occur concurrently. Let’s compare the performance of two different implementations of function $f(x, y) = x^2 + y^2$:

In [84]:
def python_f(x, y):
    return [x**2 + y**2 for (x, y) in zip(x, y)]


def numpy_f(x, y):
    return x**2 + y**2

Let's calculate the values at many `x` and `y` points:

In [85]:
# Python
x, y = range(1000), range(1000)
%timeit python_f(x, y)

1.2 ms ± 73.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [86]:
# NumPy
x, y = np.arange(1000), np.arange(1000)
%timeit numpy_f(x, y)

7.85 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


The NumPy version is about 170x faster by vectorising the for loop, that is the devil that hinders the performance of Python code. Whenever possible, avoid explicit foo loops in Python. Apart from the vectorisation of explicit arithmetic operations, we can also vectorise for loops with conditions inside by using NumPy functions such as `np.where`. See the example below:

In [87]:
# Python version
def python_f2(x, mask):
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if mask[i, j] > 0.6:
                x[i, j] = 1.
            elif mask[i, j] < 0.3:
                x[i, j] = -1.
            else:
                x[i, j] = 0.
                

# NumPy version
def numpy_f2(x, mask):
    x[np.where(mask > 0.6)] = 1.
    x[np.where(mask < 0.3)] = -1.
    x[np.where(np.logical_and(mask <= 0.6, mask >= 0.3))] = 0.

In [88]:
X = np.arange(10000).reshape(100, 100)
mask = np.random.rand(100, 100)
%timeit python_f2(X, mask)

7.41 ms ± 349 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [89]:
%timeit numpy_f2(X, mask)

455 µs ± 9.62 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


The examples described above are straightforward for vectorisation because the problems to be solved are inherently vectorisable and users can identify where the code can be vectorised without too much effort. However, in many cases vectorizability of problems is implicitly and users need to rethink the problems to make them vectorisable by using a different algorithm or inventing a new one. This requires not only a profound understanding on NumPy, but also significant practical experience on solving such problems.

Let’s consider a simple problem: compute the sum of $A[i, j] \times i \times j$ where $A[i, j]$ is a 2D array and $i, j$ are indices. The simple implementation can be written to:

In [90]:
def python_f3(A):
    val = 0.
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            val += A[i, j] * i * j
    return val

In [91]:
A = np.arange(30000, dtype=np.float64).reshape(300, 100)
%timeit python_f3(A)

28.4 ms ± 2.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [92]:
def numpy_f3(A):
    idx_i = np.tile(np.arange(A.shape[0])[:, np.newaxis], (1, A.shape[1]))
    idx_j = np.tile(np.arange(A.shape[1]), (A.shape[0], 1))
    return np.sum(np.sum(A * idx_i * idx_j))

%timeit numpy_f3(A)

422 µs ± 16.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Now the vectorised version is approximately 70x faster. To make the operation $A[i, j] * i * j$ vectorisable, we have constructed two new 2D arrays `idx_i` and `idx_j` that have the same shape as that of array `A` and contain the index values corresponding to each $A[i, j]$.

We can even make it better by using `broadcasting`. `idx_i` and `idx_j` are 2D arrays consisting of repeated vectors in column and row respectively. So we don’t have to construct such two 2D arrays `idx_i` and `idx_j` because NumPy will repeat them automatically by following its broadcasting rules when operation occurs. See  a better implementation below:   

In [93]:
def numpy_f3_bd(A):
    idx_i = np.arange(A.shape[0])[:, np.newaxis]
    idx_j = np.arange(A.shape[1])
    return np.sum(np.sum(A * idx_i * idx_j))

%timeit numpy_f3_bd(A)

181 µs ± 39.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


A better version means: extra ~2.5x performance gain and less code. 

As you can see, vectorisation can improve the computational performance dramatically with several orders of magnitude for many cases. Explicit implementation is always straightforward and logically clear, but it sacrifices computational efficiency. if speed is your concern, first try to rethink your problems and find alternatives that might be complicated logically but more efficient in the speed of your code. Then optimise the specific pieces of the code (functions, for loops and etc) if possiable.  

------

### More reading
* [Scipy lectures - NumPy](https://www.scipy-lectures.org/intro/numpy/index.html)
* [NumPy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)
* [From Python to NumPy](https://github.com/rougier/from-python-to-numpy)