### Exercises: answers

------


In [1]:
from __future__ import print_function  # to make sure that the print statement works with both Python 2 and 3.
import numpy as np

### L03-Introduction to Python language
##### Q1:
Create a Virtual Environment of Python 2 or 3 and install the following packages: *numpy*, *scipy* and *matplotlib* within the created Virtual Environment.

* Python 2

```	
virtualenv myproj_vm
```

* Python 3

```
python3 -m venv myproj_vm
```

Within the folder *myproj_vm*, a copy of Python that has no external packages installed has been created. 

Install a package within VM:
* On linux

```
/path-to-VM/bin/pip install numpy
/path-to-VM/bin/pip install scipy
/path-to-VM/bin/pip install matplotlib
```

* On Windows

```
\path-to-VM\Scripts\pip.exe install numpy
\path-to-VM\Scripts\pip.exe install scipy
\path-to-VM\Scripts\pip.exe install matplotlib
```

##### Q2:
Use list comprehension to create a Python list containing $[0^2 + 1, 1^2 + 1, 2^2 + 1, ......, 30^2 + 1]$ and calculate the sum of all elements.


##### Q3:

The value of $\pi$ can be computed by: $$\pi = \sqrt{12} \sum_{k=0}^{\infty} \frac{(-\frac{1}{3})^k}{2k+1} $$
Write a Python function `cal_pi` to calculate the value of $\pi$ using the formula above, and apply the function to compute an approximation of $\pi$ with $k=200$.

See *cal_pi.py*.

##### Q3:

The value of $\pi$ can be computed by: $$\pi = \sqrt{12} \sum_{k=0}^{\infty} \frac{(-\frac{1}{3})^k}{2k+1} $$
Write a Python function `cal_pi` to calculate the value of $\pi$ using the formula above, and apply the function to compute an approximation of $\pi$ with $k=200$.

See *cal_pi.py*.

##### Q4:
Write a Python function `diff2` to compute the second-order derivative of function $f(x)$: $$f''(x) \approx \lim_{h \to 0}\frac{f(x+h) - 2f(x) + f(x-h)}{h^2}$$
Apply `diff2` to differentiate $f(x) = x^{4}$ at $x = 1$. The result can be computed easily by hand and it is 12. So you can use this number to verify your Python code.

See *diff2.py*.

##### Q5:
Write a Python class *Line* to represent a straight line in the Cartesian plane. The class consists of a constructor that takes two points (two lists or tuples, e.g. [x1, y1] and [x2, y2]) as the input, and a method that computes the `y` value by giving a `x`. Apply the class to points (0, 0) and (10, 10) and calculate the `y` value at $x = 5$.

See *Line.py*.

##### Q6:
Reimplement the second-order derivative function `diff2` mentioned in question 4 by using Python class. Apply the class to differentiate $f(x) = x^{4}$ at $x = 1$.

See *Derivative2.py*.

### L04-NumPy
##### Q7:
Create a vector with values ranging from `10` to `20`.

In [2]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### Q8:
Create a vector of size 10. The third element is `1` and the rest are `0`.

In [3]:
A = np.zeros(10)
A[2] = 1
A

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

##### Q9:
Create a 4x4 2D array with values ranging from `0` to `15`.

In [4]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

##### Q10:
Create a 4x4 2D array with values ranging from `0` to `15`. Assign `-1` to elements which are greater than 3 and less than 10.

In [5]:
A = np.arange(16).reshape(4, 4)
A[np.logical_and(A > 3, A < 10)] = -1
A

array([[ 0,  1,  2,  3],
       [-1, -1, -1, -1],
       [-1, -1, 10, 11],
       [12, 13, 14, 15]])

##### Q11:
Create a 4x4 2D array with values ranging from `0` to `15`. Swap the first two rows.

In [6]:
A = np.arange(16).reshape(4, 4)
A[[0, 1]] = A[[1, 0]]
A

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

##### Q12:
Create a vector of size 10 with values from `0` to `20`, excluding `20`.

In [6]:
A = np.linspace(0, 20, 10, endpoint=False)
A

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

##### Q13:
Create a 3x6 2D array with random integers. Subtract the mean of each row of the 2D array.

In [8]:
A = np.random.randint(10, size=(3, 6))
print(A)
B = A - A.mean(axis=1, keepdims=True)
B

[[1 9 8 2 5 7]
 [5 7 3 5 0 2]
 [2 7 7 3 0 5]]


array([[-4.33333333,  3.66666667,  2.66666667, -3.33333333, -0.33333333,
         1.66666667],
       [ 1.33333333,  3.33333333, -0.66666667,  1.33333333, -3.66666667,
        -1.66666667],
       [-2.        ,  3.        ,  3.        , -1.        , -4.        ,
         1.        ]])

##### Q14:
Consider a 3D array with dimension (3, 4, 5). Multiply it by a 2D array with dimension (3, 4).

In [9]:
A = np.random.randint(10, size=(3, 4, 5))
B = np.random.randint(5, size=(3, 4))
A * B[:, :, None]

# or
# A * B[:, :, np.newaxis]

array([[[ 0, 28,  4, 32,  8],
        [ 7,  4,  9,  3,  5],
        [ 0,  0,  0,  0,  0],
        [ 2,  5,  7,  4,  5]],

       [[ 6,  0,  4,  2, 12],
        [ 1,  4,  4,  7,  2],
        [27,  6,  6, 15, 21],
        [ 7,  5,  0,  2,  8]],

       [[28,  4, 12, 24, 20],
        [24,  0, 27, 15, 21],
        [ 0,  0,  0,  0,  0],
        [ 8,  6,  3,  5,  1]]])

##### Q15:
Consider a vector of size 3 contains the coordinates of a point P in the Cartesian plane, and a 2D array of dimension (3, 10) comprises the coordinates of other 10 points. Calculate the distance between point P and each point of the 2D array.

In [10]:
A = np.array([0, 0, 0])
B = np.random.randint(10, size=(3, 10))
np.sqrt(np.sum((B - A[:, None])**2, axis=0))

array([ 9.64365076,  9.05538514,  6.70820393, 10.48808848, 11.40175425,
        8.71779789,  9.05538514,  9.8488578 ,  6.55743852, 11.04536102])

##### Q16:
List all the constants provided by the SciPy constants package.

In [11]:
from scipy import constants
dir(constants)

['Avogadro',
 'Boltzmann',
 'Btu',
 'Btu_IT',
 'Btu_th',
 'ConstantWarning',
 'G',
 'Julian_year',
 'N_A',
 'Planck',
 'R',
 'Rydberg',
 'Stefan_Boltzmann',
 'Wien',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_obsolete_constants',
 'absolute_import',
 'acre',
 'alpha',
 'angstrom',
 'arcmin',
 'arcminute',
 'arcsec',
 'arcsecond',
 'astronomical_unit',
 'atm',
 'atmosphere',
 'atomic_mass',
 'atto',
 'au',
 'bar',
 'barrel',
 'bbl',
 'blob',
 'c',
 'calorie',
 'calorie_IT',
 'calorie_th',
 'carat',
 'centi',
 'codata',
 'constants',
 'convert_temperature',
 'day',
 'deci',
 'degree',
 'degree_Fahrenheit',
 'deka',
 'division',
 'dyn',
 'dyne',
 'e',
 'eV',
 'electron_mass',
 'electron_volt',
 'elementary_charge',
 'epsilon_0',
 'erg',
 'exa',
 'exbi',
 'femto',
 'fermi',
 'find',
 'fine_structure',
 'fluid_ounce',
 'fluid_ounce_US',
 'fluid_ounce_imp',
 'foot',
 'g',
 'gallon',
 'gallon_US

##### Q17:
Consider a set of discreate points: $x = np.linspace(0, 2\pi, 10), y = \sin(x^{2/3})$. Interpolate them onto a new set of x points: $x = np.linspace(0, 2\pi, 50)$ using linear and cubic methods. Plot the raw and interpolated data in one figure.

See *interp.py*.

##### Q18:
Integrate function $f(x) = e^{x^2}$ over `0` to `1` using two different methods.

In [12]:
from scipy import integrate

def f(x):
    return np.exp(x**2)

# use quad function
I = integrate.quad(f, 0, 1)
print(I[0])

# use Simpson rules
x = np.linspace(0, 1, 50)
y = np.exp(x**2)
print(integrate.simps(y, x))

1.4626517459071815
1.4626580890505754


##### Q19:
Solve the second-order ODE $y'' + y' + y = \cos(x), \quad y(0) = y'(0) = 0$ over `0` to `20`, and plot the numerical solution.

See *ode2.py*.

##### Q20:
Solve the following linear equations for the x and y values: $$2x + 5y = 20$$ $$x + 3y = 16$$

In [13]:
from scipy import linalg

A = np.array([[2, 5], [1, 3]])
B = np.array([20, 16])
print(linalg.solve(A, B))

[-20.  12.]


##### Q21:
Find the root of function $x^2 + \cos(2x) + \sin(2x) = 0$ with an initial guess of 0.1.

In [14]:
from scipy import optimize

def f(x):
    return x*2 + np.cos(2*x) + np.sin(2*x)

print(optimize.root(f, 0.1))

    fjac: array([[-1.]])
     fun: array([-5.55111512e-17])
 message: 'The solution converged.'
    nfev: 8
     qtf: array([-4.25848246e-12])
       r: array([-4.67693405])
  status: 1
 success: True
       x: array([-0.22831235])
